FROM python:3
WORKDIR ./purbee_backend/backend_source
COPY . .
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5000
ENV FLASK_ENV=development
ENV FLASK_APP=./backend_source/app.py
#CMD ["flask", "run", "--host=0.0.0.0"]
#CMD ["python", "./backend_source/app.py"]
ENTRYPOINT ["flask"]

CMD ["run", "--host=0.0.0.0"]
