FROM python:3
WORKDIR ./purbee_backend/backend_source
COPY . .
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5000
ENV FLASK_ENV=development
ENV FLASK_APP=./app.py
CMD ["python", "./app.py"]
