FROM python:3
WORKDIR /usr/src/app
COPY ../. .
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5000
ENV FLASK_ENV=development
#ENV FLASK_APP=./purbee_backend/backend_source/app.py
#CMD ["flask", "run", "--host=0.0.0.0"]
CMD ["python", "./app.py"]}